server:
  http:
    addr: 0.0.0.0:8100
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9100
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:123qwe@tcp(116.63.146.14:3301)/test
  redis:
    addr: 8.130.28.195:6372
    read_timeout: 0.2s
    write_timeout: 0.2s
