// Code generated by entc, DO NOT EDIT.

package device

import (
	"time"
)

const (
	// Label holds the string label denoting the device type in the database.
	Label = "device"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldHardwareKey holds the string denoting the hardwarekey field in the database.
	FieldHardwareKey = "hardware_key"
	// FieldDefaultLayoutId holds the string denoting the defaultlayoutid field in the database.
	FieldDefaultLayoutId = "default_layout_id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldStoreNumber holds the string denoting the storenumber field in the database.
	FieldStoreNumber = "store_number"
	// FieldCreatedAt holds the string denoting the createdat field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the device in the database.
	Table = "devices"
)

// Columns holds all SQL columns for device fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldHardwareKey,
	FieldDefaultLayoutId,
	FieldStatus,
	FieldStoreNumber,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "createdAt" field.
	DefaultCreatedAt func() time.Time
)
