// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.15.8
// source: api/layout/v4/layout.proto

package v4

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the user's name.
type LayoutResourceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HardwareKey string `protobuf:"bytes,1,opt,name=hardwareKey,proto3" json:"hardwareKey,omitempty"`
}

func (x *LayoutResourceRequest) Reset() {
	*x = LayoutResourceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_layout_v4_layout_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LayoutResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LayoutResourceRequest) ProtoMessage() {}

func (x *LayoutResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_layout_v4_layout_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LayoutResourceRequest.ProtoReflect.Descriptor instead.
func (*LayoutResourceRequest) Descriptor() ([]byte, []int) {
	return file_api_layout_v4_layout_proto_rawDescGZIP(), []int{0}
}

func (x *LayoutResourceRequest) GetHardwareKey() string {
	if x != nil {
		return x.HardwareKey
	}
	return ""
}

// The response message containing the greetings
type LayoutResourceReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Layouts   []*LayoutResourceReply_ResourceLayout   `protobuf:"bytes,1,rep,name=layouts,proto3" json:"layouts,omitempty"`
	Schedules []*LayoutResourceReply_ResourceSchedule `protobuf:"bytes,2,rep,name=schedules,proto3" json:"schedules,omitempty"`
	Resources []*LayoutResourceReply_Resource         `protobuf:"bytes,3,rep,name=resources,proto3" json:"resources,omitempty"`
}

func (x *LayoutResourceReply) Reset() {
	*x = LayoutResourceReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_layout_v4_layout_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LayoutResourceReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LayoutResourceReply) ProtoMessage() {}

func (x *LayoutResourceReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_layout_v4_layout_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LayoutResourceReply.ProtoReflect.Descriptor instead.
func (*LayoutResourceReply) Descriptor() ([]byte, []int) {
	return file_api_layout_v4_layout_proto_rawDescGZIP(), []int{1}
}

func (x *LayoutResourceReply) GetLayouts() []*LayoutResourceReply_ResourceLayout {
	if x != nil {
		return x.Layouts
	}
	return nil
}

func (x *LayoutResourceReply) GetSchedules() []*LayoutResourceReply_ResourceSchedule {
	if x != nil {
		return x.Schedules
	}
	return nil
}

func (x *LayoutResourceReply) GetResources() []*LayoutResourceReply_Resource {
	if x != nil {
		return x.Resources
	}
	return nil
}

type LayoutResourceReply_ResourceLayout struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Md5  string `protobuf:"bytes,3,opt,name=md5,proto3" json:"md5,omitempty"`
	Path string `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *LayoutResourceReply_ResourceLayout) Reset() {
	*x = LayoutResourceReply_ResourceLayout{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_layout_v4_layout_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LayoutResourceReply_ResourceLayout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LayoutResourceReply_ResourceLayout) ProtoMessage() {}

func (x *LayoutResourceReply_ResourceLayout) ProtoReflect() protoreflect.Message {
	mi := &file_api_layout_v4_layout_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LayoutResourceReply_ResourceLayout.ProtoReflect.Descriptor instead.
func (*LayoutResourceReply_ResourceLayout) Descriptor() ([]byte, []int) {
	return file_api_layout_v4_layout_proto_rawDescGZIP(), []int{1, 0}
}

func (x *LayoutResourceReply_ResourceLayout) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LayoutResourceReply_ResourceLayout) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LayoutResourceReply_ResourceLayout) GetMd5() string {
	if x != nil {
		return x.Md5
	}
	return ""
}

func (x *LayoutResourceReply_ResourceLayout) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type LayoutResourceReply_ResourceSchedule struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name   string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Detail string `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
}

func (x *LayoutResourceReply_ResourceSchedule) Reset() {
	*x = LayoutResourceReply_ResourceSchedule{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_layout_v4_layout_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LayoutResourceReply_ResourceSchedule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LayoutResourceReply_ResourceSchedule) ProtoMessage() {}

func (x *LayoutResourceReply_ResourceSchedule) ProtoReflect() protoreflect.Message {
	mi := &file_api_layout_v4_layout_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LayoutResourceReply_ResourceSchedule.ProtoReflect.Descriptor instead.
func (*LayoutResourceReply_ResourceSchedule) Descriptor() ([]byte, []int) {
	return file_api_layout_v4_layout_proto_rawDescGZIP(), []int{1, 1}
}

func (x *LayoutResourceReply_ResourceSchedule) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LayoutResourceReply_ResourceSchedule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LayoutResourceReply_ResourceSchedule) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type LayoutResourceReply_Resource struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Md5  string `protobuf:"bytes,3,opt,name=md5,proto3" json:"md5,omitempty"`
	Path string `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *LayoutResourceReply_Resource) Reset() {
	*x = LayoutResourceReply_Resource{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_layout_v4_layout_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LayoutResourceReply_Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LayoutResourceReply_Resource) ProtoMessage() {}

func (x *LayoutResourceReply_Resource) ProtoReflect() protoreflect.Message {
	mi := &file_api_layout_v4_layout_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LayoutResourceReply_Resource.ProtoReflect.Descriptor instead.
func (*LayoutResourceReply_Resource) Descriptor() ([]byte, []int) {
	return file_api_layout_v4_layout_proto_rawDescGZIP(), []int{1, 2}
}

func (x *LayoutResourceReply_Resource) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LayoutResourceReply_Resource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LayoutResourceReply_Resource) GetMd5() string {
	if x != nil {
		return x.Md5
	}
	return ""
}

func (x *LayoutResourceReply_Resource) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

var File_api_layout_v4_layout_proto protoreflect.FileDescriptor

var file_api_layout_v4_layout_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x61, 0x70, 0x69, 0x2f, 0x6c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x2f, 0x76, 0x34, 0x2f,
	0x6c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x6c, 0x61,
	0x79, 0x6f, 0x75, 0x74, 0x2e, 0x76, 0x34, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x39, 0x0a, 0x15, 0x4c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x52,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20,
	0x0a, 0x0b, 0x68, 0x61, 0x72, 0x64, 0x77, 0x61, 0x72, 0x65, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x68, 0x61, 0x72, 0x64, 0x77, 0x61, 0x72, 0x65, 0x4b, 0x65, 0x79,
	0x22, 0xf6, 0x03, 0x0a, 0x13, 0x4c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x52, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x47, 0x0a, 0x07, 0x6c, 0x61, 0x79, 0x6f,
	0x75, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x6c, 0x61, 0x79, 0x6f,
	0x75, 0x74, 0x2e, 0x76, 0x34, 0x2e, 0x4c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x52, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x4c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x52, 0x07, 0x6c, 0x61, 0x79, 0x6f, 0x75, 0x74,
	0x73, 0x12, 0x4d, 0x0a, 0x09, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x6c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x2e, 0x76, 0x34,
	0x2e, 0x4c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x53, 0x63, 0x68,
	0x65, 0x64, 0x75, 0x6c, 0x65, 0x52, 0x09, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x73,
	0x12, 0x45, 0x0a, 0x09, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x6c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x2e, 0x76, 0x34, 0x2e,
	0x4c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x09, 0x72, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x1a, 0x5a, 0x0a, 0x0e, 0x52, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x4c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x6d, 0x64, 0x35, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x64, 0x35, 0x12,
	0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70,
	0x61, 0x74, 0x68, 0x1a, 0x4e, 0x0a, 0x10, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x53,
	0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x64,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x1a, 0x54, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x64, 0x35, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6d, 0x64, 0x35, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x32, 0x83, 0x01, 0x0a, 0x06, 0x4c, 0x61,
	0x79, 0x6f, 0x75, 0x74, 0x12, 0x79, 0x0a, 0x15, 0x67, 0x65, 0x74, 0x44, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x20, 0x2e,
	0x6c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x2e, 0x76, 0x34, 0x2e, 0x4c, 0x61, 0x79, 0x6f, 0x75, 0x74,
	0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1e, 0x2e, 0x6c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x2e, 0x76, 0x34, 0x2e, 0x4c, 0x61, 0x79, 0x6f,
	0x75, 0x74, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22,
	0x1e, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x18, 0x12, 0x16, 0x2f, 0x67, 0x65, 0x74, 0x44, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x42,
	0x42, 0x0a, 0x18, 0x64, 0x65, 0x76, 0x2e, 0x6b, 0x72, 0x61, 0x74, 0x6f, 0x73, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x6c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x2e, 0x76, 0x34, 0x42, 0x08, 0x6c, 0x61, 0x79,
	0x6f, 0x75, 0x74, 0x56, 0x34, 0x50, 0x01, 0x5a, 0x1a, 0x72, 0x70, 0x63, 0x43, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x2f, 0x76, 0x34,
	0x3b, 0x76, 0x34, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_layout_v4_layout_proto_rawDescOnce sync.Once
	file_api_layout_v4_layout_proto_rawDescData = file_api_layout_v4_layout_proto_rawDesc
)

func file_api_layout_v4_layout_proto_rawDescGZIP() []byte {
	file_api_layout_v4_layout_proto_rawDescOnce.Do(func() {
		file_api_layout_v4_layout_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_layout_v4_layout_proto_rawDescData)
	})
	return file_api_layout_v4_layout_proto_rawDescData
}

var file_api_layout_v4_layout_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_layout_v4_layout_proto_goTypes = []interface{}{
	(*LayoutResourceRequest)(nil),                // 0: layout.v4.LayoutResourceRequest
	(*LayoutResourceReply)(nil),                  // 1: layout.v4.LayoutResourceReply
	(*LayoutResourceReply_ResourceLayout)(nil),   // 2: layout.v4.LayoutResourceReply.ResourceLayout
	(*LayoutResourceReply_ResourceSchedule)(nil), // 3: layout.v4.LayoutResourceReply.ResourceSchedule
	(*LayoutResourceReply_Resource)(nil),         // 4: layout.v4.LayoutResourceReply.Resource
}
var file_api_layout_v4_layout_proto_depIdxs = []int32{
	2, // 0: layout.v4.LayoutResourceReply.layouts:type_name -> layout.v4.LayoutResourceReply.ResourceLayout
	3, // 1: layout.v4.LayoutResourceReply.schedules:type_name -> layout.v4.LayoutResourceReply.ResourceSchedule
	4, // 2: layout.v4.LayoutResourceReply.resources:type_name -> layout.v4.LayoutResourceReply.Resource
	0, // 3: layout.v4.Layout.getDeviceResourceList:input_type -> layout.v4.LayoutResourceRequest
	1, // 4: layout.v4.Layout.getDeviceResourceList:output_type -> layout.v4.LayoutResourceReply
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_layout_v4_layout_proto_init() }
func file_api_layout_v4_layout_proto_init() {
	if File_api_layout_v4_layout_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_layout_v4_layout_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LayoutResourceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_layout_v4_layout_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LayoutResourceReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_layout_v4_layout_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LayoutResourceReply_ResourceLayout); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_layout_v4_layout_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LayoutResourceReply_ResourceSchedule); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_layout_v4_layout_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LayoutResourceReply_Resource); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_layout_v4_layout_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_layout_v4_layout_proto_goTypes,
		DependencyIndexes: file_api_layout_v4_layout_proto_depIdxs,
		MessageInfos:      file_api_layout_v4_layout_proto_msgTypes,
	}.Build()
	File_api_layout_v4_layout_proto = out.File
	file_api_layout_v4_layout_proto_rawDesc = nil
	file_api_layout_v4_layout_proto_goTypes = nil
	file_api_layout_v4_layout_proto_depIdxs = nil
}
