// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v4

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BffDeviceClient is the client API for BffDevice service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BffDeviceClient interface {
	// 注册或更新设备
	RegisteDevice(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterReply, error)
	// 修改设备名称
	ChangeName(ctx context.Context, in *ChangeNameRequest, opts ...grpc.CallOption) (*ChangeNameReply, error)
	// 获取设备信息
	GetDevice(ctx context.Context, in *GetDeviceRequest, opts ...grpc.CallOption) (*GetDeviceReply, error)
	// 获取设备信息
	GetDeviceDisplay(ctx context.Context, in *GetDeviceDisplayRequest, opts ...grpc.CallOption) (*GetDeviceDisplayReply, error)
}

type bffDeviceClient struct {
	cc grpc.ClientConnInterface
}

func NewBffDeviceClient(cc grpc.ClientConnInterface) BffDeviceClient {
	return &bffDeviceClient{cc}
}

func (c *bffDeviceClient) RegisteDevice(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterReply, error) {
	out := new(RegisterReply)
	err := c.cc.Invoke(ctx, "/device.v4.BffDevice/registeDevice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bffDeviceClient) ChangeName(ctx context.Context, in *ChangeNameRequest, opts ...grpc.CallOption) (*ChangeNameReply, error) {
	out := new(ChangeNameReply)
	err := c.cc.Invoke(ctx, "/device.v4.BffDevice/changeName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bffDeviceClient) GetDevice(ctx context.Context, in *GetDeviceRequest, opts ...grpc.CallOption) (*GetDeviceReply, error) {
	out := new(GetDeviceReply)
	err := c.cc.Invoke(ctx, "/device.v4.BffDevice/getDevice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bffDeviceClient) GetDeviceDisplay(ctx context.Context, in *GetDeviceDisplayRequest, opts ...grpc.CallOption) (*GetDeviceDisplayReply, error) {
	out := new(GetDeviceDisplayReply)
	err := c.cc.Invoke(ctx, "/device.v4.BffDevice/getDeviceDisplay", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BffDeviceServer is the server API for BffDevice service.
// All implementations must embed UnimplementedBffDeviceServer
// for forward compatibility
type BffDeviceServer interface {
	// 注册或更新设备
	RegisteDevice(context.Context, *RegisterRequest) (*RegisterReply, error)
	// 修改设备名称
	ChangeName(context.Context, *ChangeNameRequest) (*ChangeNameReply, error)
	// 获取设备信息
	GetDevice(context.Context, *GetDeviceRequest) (*GetDeviceReply, error)
	// 获取设备信息
	GetDeviceDisplay(context.Context, *GetDeviceDisplayRequest) (*GetDeviceDisplayReply, error)
	mustEmbedUnimplementedBffDeviceServer()
}

// UnimplementedBffDeviceServer must be embedded to have forward compatible implementations.
type UnimplementedBffDeviceServer struct {
}

func (UnimplementedBffDeviceServer) RegisteDevice(context.Context, *RegisterRequest) (*RegisterReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisteDevice not implemented")
}
func (UnimplementedBffDeviceServer) ChangeName(context.Context, *ChangeNameRequest) (*ChangeNameReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeName not implemented")
}
func (UnimplementedBffDeviceServer) GetDevice(context.Context, *GetDeviceRequest) (*GetDeviceReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDevice not implemented")
}
func (UnimplementedBffDeviceServer) GetDeviceDisplay(context.Context, *GetDeviceDisplayRequest) (*GetDeviceDisplayReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDeviceDisplay not implemented")
}
func (UnimplementedBffDeviceServer) mustEmbedUnimplementedBffDeviceServer() {}

// UnsafeBffDeviceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BffDeviceServer will
// result in compilation errors.
type UnsafeBffDeviceServer interface {
	mustEmbedUnimplementedBffDeviceServer()
}

func RegisterBffDeviceServer(s grpc.ServiceRegistrar, srv BffDeviceServer) {
	s.RegisterService(&BffDevice_ServiceDesc, srv)
}

func _BffDevice_RegisteDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BffDeviceServer).RegisteDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/device.v4.BffDevice/registeDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BffDeviceServer).RegisteDevice(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BffDevice_ChangeName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BffDeviceServer).ChangeName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/device.v4.BffDevice/changeName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BffDeviceServer).ChangeName(ctx, req.(*ChangeNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BffDevice_GetDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BffDeviceServer).GetDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/device.v4.BffDevice/getDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BffDeviceServer).GetDevice(ctx, req.(*GetDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BffDevice_GetDeviceDisplay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeviceDisplayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BffDeviceServer).GetDeviceDisplay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/device.v4.BffDevice/getDeviceDisplay",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BffDeviceServer).GetDeviceDisplay(ctx, req.(*GetDeviceDisplayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BffDevice_ServiceDesc is the grpc.ServiceDesc for BffDevice service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BffDevice_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "device.v4.BffDevice",
	HandlerType: (*BffDeviceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "registeDevice",
			Handler:    _BffDevice_RegisteDevice_Handler,
		},
		{
			MethodName: "changeName",
			Handler:    _BffDevice_ChangeName_Handler,
		},
		{
			MethodName: "getDevice",
			Handler:    _BffDevice_GetDevice_Handler,
		},
		{
			MethodName: "getDeviceDisplay",
			Handler:    _BffDevice_GetDeviceDisplay_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/device/v4/bff_device.proto",
}
