// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"rpcClient/app/device/service/ent/device"
	"rpcClient/app/device/service/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DeviceUpdate is the builder for updating Device entities.
type DeviceUpdate struct {
	config
	hooks    []Hook
	mutation *DeviceMutation
}

// Where appends a list predicates to the DeviceUpdate builder.
func (du *DeviceUpdate) Where(ps ...predicate.Device) *DeviceUpdate {
	du.mutation.Where(ps...)
	return du
}

// SetName sets the "name" field.
func (du *DeviceUpdate) SetName(s string) *DeviceUpdate {
	du.mutation.SetName(s)
	return du
}

// SetNillableName sets the "name" field if the given value is not nil.
func (du *DeviceUpdate) SetNillableName(s *string) *DeviceUpdate {
	if s != nil {
		du.SetName(*s)
	}
	return du
}

// ClearName clears the value of the "name" field.
func (du *DeviceUpdate) ClearName() *DeviceUpdate {
	du.mutation.ClearName()
	return du
}

// SetHardwareKey sets the "hardwareKey" field.
func (du *DeviceUpdate) SetHardwareKey(s string) *DeviceUpdate {
	du.mutation.SetHardwareKey(s)
	return du
}

// SetNillableHardwareKey sets the "hardwareKey" field if the given value is not nil.
func (du *DeviceUpdate) SetNillableHardwareKey(s *string) *DeviceUpdate {
	if s != nil {
		du.SetHardwareKey(*s)
	}
	return du
}

// ClearHardwareKey clears the value of the "hardwareKey" field.
func (du *DeviceUpdate) ClearHardwareKey() *DeviceUpdate {
	du.mutation.ClearHardwareKey()
	return du
}

// SetDefaultLayoutId sets the "defaultLayoutId" field.
func (du *DeviceUpdate) SetDefaultLayoutId(i int32) *DeviceUpdate {
	du.mutation.ResetDefaultLayoutId()
	du.mutation.SetDefaultLayoutId(i)
	return du
}

// SetNillableDefaultLayoutId sets the "defaultLayoutId" field if the given value is not nil.
func (du *DeviceUpdate) SetNillableDefaultLayoutId(i *int32) *DeviceUpdate {
	if i != nil {
		du.SetDefaultLayoutId(*i)
	}
	return du
}

// AddDefaultLayoutId adds i to the "defaultLayoutId" field.
func (du *DeviceUpdate) AddDefaultLayoutId(i int32) *DeviceUpdate {
	du.mutation.AddDefaultLayoutId(i)
	return du
}

// ClearDefaultLayoutId clears the value of the "defaultLayoutId" field.
func (du *DeviceUpdate) ClearDefaultLayoutId() *DeviceUpdate {
	du.mutation.ClearDefaultLayoutId()
	return du
}

// SetStatus sets the "status" field.
func (du *DeviceUpdate) SetStatus(i int32) *DeviceUpdate {
	du.mutation.ResetStatus()
	du.mutation.SetStatus(i)
	return du
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (du *DeviceUpdate) SetNillableStatus(i *int32) *DeviceUpdate {
	if i != nil {
		du.SetStatus(*i)
	}
	return du
}

// AddStatus adds i to the "status" field.
func (du *DeviceUpdate) AddStatus(i int32) *DeviceUpdate {
	du.mutation.AddStatus(i)
	return du
}

// ClearStatus clears the value of the "status" field.
func (du *DeviceUpdate) ClearStatus() *DeviceUpdate {
	du.mutation.ClearStatus()
	return du
}

// SetStoreNumber sets the "storeNumber" field.
func (du *DeviceUpdate) SetStoreNumber(s string) *DeviceUpdate {
	du.mutation.SetStoreNumber(s)
	return du
}

// SetNillableStoreNumber sets the "storeNumber" field if the given value is not nil.
func (du *DeviceUpdate) SetNillableStoreNumber(s *string) *DeviceUpdate {
	if s != nil {
		du.SetStoreNumber(*s)
	}
	return du
}

// ClearStoreNumber clears the value of the "storeNumber" field.
func (du *DeviceUpdate) ClearStoreNumber() *DeviceUpdate {
	du.mutation.ClearStoreNumber()
	return du
}

// Mutation returns the DeviceMutation object of the builder.
func (du *DeviceUpdate) Mutation() *DeviceMutation {
	return du.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (du *DeviceUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(du.hooks) == 0 {
		affected, err = du.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*DeviceMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			du.mutation = mutation
			affected, err = du.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(du.hooks) - 1; i >= 0; i-- {
			if du.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = du.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, du.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (du *DeviceUpdate) SaveX(ctx context.Context) int {
	affected, err := du.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (du *DeviceUpdate) Exec(ctx context.Context) error {
	_, err := du.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (du *DeviceUpdate) ExecX(ctx context.Context) {
	if err := du.Exec(ctx); err != nil {
		panic(err)
	}
}

func (du *DeviceUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   device.Table,
			Columns: device.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: device.FieldID,
			},
		},
	}
	if ps := du.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := du.mutation.Name(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: device.FieldName,
		})
	}
	if du.mutation.NameCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: device.FieldName,
		})
	}
	if value, ok := du.mutation.HardwareKey(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: device.FieldHardwareKey,
		})
	}
	if du.mutation.HardwareKeyCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: device.FieldHardwareKey,
		})
	}
	if value, ok := du.mutation.DefaultLayoutId(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt32,
			Value:  value,
			Column: device.FieldDefaultLayoutId,
		})
	}
	if value, ok := du.mutation.AddedDefaultLayoutId(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt32,
			Value:  value,
			Column: device.FieldDefaultLayoutId,
		})
	}
	if du.mutation.DefaultLayoutIdCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeInt32,
			Column: device.FieldDefaultLayoutId,
		})
	}
	if value, ok := du.mutation.Status(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt32,
			Value:  value,
			Column: device.FieldStatus,
		})
	}
	if value, ok := du.mutation.AddedStatus(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt32,
			Value:  value,
			Column: device.FieldStatus,
		})
	}
	if du.mutation.StatusCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeInt32,
			Column: device.FieldStatus,
		})
	}
	if value, ok := du.mutation.StoreNumber(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: device.FieldStoreNumber,
		})
	}
	if du.mutation.StoreNumberCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: device.FieldStoreNumber,
		})
	}
	if du.mutation.CreatedAtCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Column: device.FieldCreatedAt,
		})
	}
	if n, err = sqlgraph.UpdateNodes(ctx, du.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{device.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return 0, err
	}
	return n, nil
}

// DeviceUpdateOne is the builder for updating a single Device entity.
type DeviceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DeviceMutation
}

// SetName sets the "name" field.
func (duo *DeviceUpdateOne) SetName(s string) *DeviceUpdateOne {
	duo.mutation.SetName(s)
	return duo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (duo *DeviceUpdateOne) SetNillableName(s *string) *DeviceUpdateOne {
	if s != nil {
		duo.SetName(*s)
	}
	return duo
}

// ClearName clears the value of the "name" field.
func (duo *DeviceUpdateOne) ClearName() *DeviceUpdateOne {
	duo.mutation.ClearName()
	return duo
}

// SetHardwareKey sets the "hardwareKey" field.
func (duo *DeviceUpdateOne) SetHardwareKey(s string) *DeviceUpdateOne {
	duo.mutation.SetHardwareKey(s)
	return duo
}

// SetNillableHardwareKey sets the "hardwareKey" field if the given value is not nil.
func (duo *DeviceUpdateOne) SetNillableHardwareKey(s *string) *DeviceUpdateOne {
	if s != nil {
		duo.SetHardwareKey(*s)
	}
	return duo
}

// ClearHardwareKey clears the value of the "hardwareKey" field.
func (duo *DeviceUpdateOne) ClearHardwareKey() *DeviceUpdateOne {
	duo.mutation.ClearHardwareKey()
	return duo
}

// SetDefaultLayoutId sets the "defaultLayoutId" field.
func (duo *DeviceUpdateOne) SetDefaultLayoutId(i int32) *DeviceUpdateOne {
	duo.mutation.ResetDefaultLayoutId()
	duo.mutation.SetDefaultLayoutId(i)
	return duo
}

// SetNillableDefaultLayoutId sets the "defaultLayoutId" field if the given value is not nil.
func (duo *DeviceUpdateOne) SetNillableDefaultLayoutId(i *int32) *DeviceUpdateOne {
	if i != nil {
		duo.SetDefaultLayoutId(*i)
	}
	return duo
}

// AddDefaultLayoutId adds i to the "defaultLayoutId" field.
func (duo *DeviceUpdateOne) AddDefaultLayoutId(i int32) *DeviceUpdateOne {
	duo.mutation.AddDefaultLayoutId(i)
	return duo
}

// ClearDefaultLayoutId clears the value of the "defaultLayoutId" field.
func (duo *DeviceUpdateOne) ClearDefaultLayoutId() *DeviceUpdateOne {
	duo.mutation.ClearDefaultLayoutId()
	return duo
}

// SetStatus sets the "status" field.
func (duo *DeviceUpdateOne) SetStatus(i int32) *DeviceUpdateOne {
	duo.mutation.ResetStatus()
	duo.mutation.SetStatus(i)
	return duo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (duo *DeviceUpdateOne) SetNillableStatus(i *int32) *DeviceUpdateOne {
	if i != nil {
		duo.SetStatus(*i)
	}
	return duo
}

// AddStatus adds i to the "status" field.
func (duo *DeviceUpdateOne) AddStatus(i int32) *DeviceUpdateOne {
	duo.mutation.AddStatus(i)
	return duo
}

// ClearStatus clears the value of the "status" field.
func (duo *DeviceUpdateOne) ClearStatus() *DeviceUpdateOne {
	duo.mutation.ClearStatus()
	return duo
}

// SetStoreNumber sets the "storeNumber" field.
func (duo *DeviceUpdateOne) SetStoreNumber(s string) *DeviceUpdateOne {
	duo.mutation.SetStoreNumber(s)
	return duo
}

// SetNillableStoreNumber sets the "storeNumber" field if the given value is not nil.
func (duo *DeviceUpdateOne) SetNillableStoreNumber(s *string) *DeviceUpdateOne {
	if s != nil {
		duo.SetStoreNumber(*s)
	}
	return duo
}

// ClearStoreNumber clears the value of the "storeNumber" field.
func (duo *DeviceUpdateOne) ClearStoreNumber() *DeviceUpdateOne {
	duo.mutation.ClearStoreNumber()
	return duo
}

// Mutation returns the DeviceMutation object of the builder.
func (duo *DeviceUpdateOne) Mutation() *DeviceMutation {
	return duo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (duo *DeviceUpdateOne) Select(field string, fields ...string) *DeviceUpdateOne {
	duo.fields = append([]string{field}, fields...)
	return duo
}

// Save executes the query and returns the updated Device entity.
func (duo *DeviceUpdateOne) Save(ctx context.Context) (*Device, error) {
	var (
		err  error
		node *Device
	)
	if len(duo.hooks) == 0 {
		node, err = duo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*DeviceMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			duo.mutation = mutation
			node, err = duo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(duo.hooks) - 1; i >= 0; i-- {
			if duo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = duo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, duo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (duo *DeviceUpdateOne) SaveX(ctx context.Context) *Device {
	node, err := duo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (duo *DeviceUpdateOne) Exec(ctx context.Context) error {
	_, err := duo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (duo *DeviceUpdateOne) ExecX(ctx context.Context) {
	if err := duo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (duo *DeviceUpdateOne) sqlSave(ctx context.Context) (_node *Device, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   device.Table,
			Columns: device.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: device.FieldID,
			},
		},
	}
	id, ok := duo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Device.ID for update")}
	}
	_spec.Node.ID.Value = id
	if fields := duo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, device.FieldID)
		for _, f := range fields {
			if !device.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != device.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := duo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := duo.mutation.Name(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: device.FieldName,
		})
	}
	if duo.mutation.NameCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: device.FieldName,
		})
	}
	if value, ok := duo.mutation.HardwareKey(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: device.FieldHardwareKey,
		})
	}
	if duo.mutation.HardwareKeyCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: device.FieldHardwareKey,
		})
	}
	if value, ok := duo.mutation.DefaultLayoutId(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt32,
			Value:  value,
			Column: device.FieldDefaultLayoutId,
		})
	}
	if value, ok := duo.mutation.AddedDefaultLayoutId(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt32,
			Value:  value,
			Column: device.FieldDefaultLayoutId,
		})
	}
	if duo.mutation.DefaultLayoutIdCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeInt32,
			Column: device.FieldDefaultLayoutId,
		})
	}
	if value, ok := duo.mutation.Status(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt32,
			Value:  value,
			Column: device.FieldStatus,
		})
	}
	if value, ok := duo.mutation.AddedStatus(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt32,
			Value:  value,
			Column: device.FieldStatus,
		})
	}
	if duo.mutation.StatusCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeInt32,
			Column: device.FieldStatus,
		})
	}
	if value, ok := duo.mutation.StoreNumber(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: device.FieldStoreNumber,
		})
	}
	if duo.mutation.StoreNumberCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: device.FieldStoreNumber,
		})
	}
	if duo.mutation.CreatedAtCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Column: device.FieldCreatedAt,
		})
	}
	_node = &Device{config: duo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, duo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{device.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	return _node, nil
}
