// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// protoc-gen-go-http v2.1.1

package v4

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

type DeviceHTTPServer interface {
	ChangeName(context.Context, *ChangeNameRequest) (*ChangeNameReply, error)
	Deploy(context.Context, *DeployRequest) (*DeployReply, error)
	Register(context.Context, *RegisterRequest) (*RegisterReply, error)
}

func RegisterDeviceHTTPServer(s *http.Server, srv DeviceHTTPServer) {
	r := s.Route("/")
	r.POST("/registerDisplay", _Device_Register0_HTTP_Handler(srv))
	r.PUT("/changeDisplayName", _Device_ChangeName0_HTTP_Handler(srv))
	r.POST("/preDeploy", _Device_Deploy0_HTTP_Handler(srv))
}

func _Device_Register0_HTTP_Handler(srv DeviceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RegisterRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/device.v4.Device/Register")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Register(ctx, req.(*RegisterRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RegisterReply)
		return ctx.Result(200, reply)
	}
}

func _Device_ChangeName0_HTTP_Handler(srv DeviceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ChangeNameRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/device.v4.Device/ChangeName")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ChangeName(ctx, req.(*ChangeNameRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ChangeNameReply)
		return ctx.Result(200, reply)
	}
}

func _Device_Deploy0_HTTP_Handler(srv DeviceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeployRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/device.v4.Device/Deploy")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Deploy(ctx, req.(*DeployRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeployReply)
		return ctx.Result(200, reply)
	}
}

type DeviceHTTPClient interface {
	ChangeName(ctx context.Context, req *ChangeNameRequest, opts ...http.CallOption) (rsp *ChangeNameReply, err error)
	Deploy(ctx context.Context, req *DeployRequest, opts ...http.CallOption) (rsp *DeployReply, err error)
	Register(ctx context.Context, req *RegisterRequest, opts ...http.CallOption) (rsp *RegisterReply, err error)
}

type DeviceHTTPClientImpl struct {
	cc *http.Client
}

func NewDeviceHTTPClient(client *http.Client) DeviceHTTPClient {
	return &DeviceHTTPClientImpl{client}
}

func (c *DeviceHTTPClientImpl) ChangeName(ctx context.Context, in *ChangeNameRequest, opts ...http.CallOption) (*ChangeNameReply, error) {
	var out ChangeNameReply
	pattern := "/changeDisplayName"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation("/device.v4.Device/ChangeName"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *DeviceHTTPClientImpl) Deploy(ctx context.Context, in *DeployRequest, opts ...http.CallOption) (*DeployReply, error) {
	var out DeployReply
	pattern := "/preDeploy"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation("/device.v4.Device/Deploy"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *DeviceHTTPClientImpl) Register(ctx context.Context, in *RegisterRequest, opts ...http.CallOption) (*RegisterReply, error) {
	var out RegisterReply
	pattern := "/registerDisplay"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation("/device.v4.Device/Register"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
